# Generated by Django 3.0.2 on 2020-01-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.VacancyStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Responce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='AbilityTest_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('solve_at', models.DateTimeField()),
                ('abilitytest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.AbilityTest')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Responce')),
            ],
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='vacancy',
            field=models.ManyToManyField(to='API.Vacancy'),
        ),
    ]
