# Generated by Django 3.0.2 on 2020-01-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200124_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
