# Generated by Django 3.0.2 on 2020-01-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200124_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='external_id',
            field=models.IntegerField(null=True),
        ),
    ]
