# Generated by Django 3.0.2 on 2020-01-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_vacancy_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='responce',
            name='external_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='abilitytest',
            name='vacancy',
            field=models.ManyToManyField(null=True, to='API.Vacancy'),
        ),
    ]
