# Generated by Django 3.0.2 on 2020-01-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200129_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitytest_response',
            name='solve_at',
            field=models.DateTimeField(null=True),
        ),
    ]
